name: Deployment Test

on:
  push:
    branches:
      - main

jobs:
  pest_test_and_static_analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src  # Set the working directory for all steps

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
          MYSQL_USER: toyeight
          MYSQL_PASSWORD: 87sjbS2dBmzd
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Copy Environment File
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Configure Database Connection
        run: |
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=test_database/' .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Migrate Database
        run: php artisan migrate

      - name: Run Tests
        run: vendor/bin/pest

      - name: Analyze with PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
